use_frameworks!

platform :ios, '10.0'

target 'RandomFactoryDemo' do
 pod 'RandomFactory', path: '../../'
 pod 'PlaceholderImages', :git => 'https://github.com/Appsaurus/PlaceholderImages'
 pod 'Avatars', :git => 'https://github.com/Appsaurus/Avatars'
 pod 'CodableExtensions', :git => 'https://github.com/Appsaurus/CodableExtensions'
 pod 'RuntimeExtensions', :git => 'https://github.com/Appsaurus/RuntimeExtensions'
 pod 'Codability', :git => 'https://github.com/Appsaurus/Codability'

end

